version: '3.4'
services:
  client:
    build:
      context: .
      target: builder-client
    ports:
     - "3000:3000"
    volumes:
     - ./public:/home/node/app/public
     - ./src:/home/node/app/src
     - ./package.json:/home/node/app/package.json
    tty: true
    environment:
      NODE_ENV: "development"